version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python3 src/main.py
        volumes:
            - ./src:/src
        ports:
            - 5000:5000